name: Continuous integration for SAW template

on:
  push:
    branches: [ js-migration ]
  pull_request:
    branches: [ js-migration ]

jobs:
  node-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.14.1
      - name: Node Install
        run: npm --prefix ./nodeApp ci ./nodeApp
      - name: Node test
        run: npm --prefix ./nodeApp test ./nodeApp
  node-deploy-webapp:
    needs: [ node-build-test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: AkhileshNS/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "saw213" # Must exist and be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "nodeApp"
          usedocker: true
          docker_build_args: |
            API_URI
  backend-test-deploy:
    needs: [ node-deploy-webapp ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Maven test & package
        run: mvn -B package -f wikidataApi/pom.xml
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          appdir: "wikidataApi"
          usedocker: true
